#!/usr/bin/env bash
# seed-vendor.sh — bootstrap the local op-reth monorepo mirror + cargo config.
#
# Idempotent. Run once on any fresh machine / CI runner / Docker build stage
# BEFORE `cargo build --locked`. Running it again is a no-op.
#
# What it does:
#   1. Derives the repo root from this script's own location (no hardcoded
#      path), so it works regardless of where the repo is checked out.
#   2. Creates a *shallow depth-1* clone of the EXACT optimism monorepo rev at
#      <repo>/.vendor/optimism if absent (~45 MB). A shallow depth-1 clone of
#      the single rev is the only minimal-checkout technique that works with
#      cargo: a blobless+sparse promisor mirror makes cargo's git fetch demand
#      a full pack ("bad pack header"); depth-1 is self-contained and offline.
#   3. Writes the GITIGNORED <repo>/.cargo/config.toml which (a) enables
#      git-fetch-with-cli and (b) source-replaces the WHOLE
#      ethereum-optimism/optimism git source onto that local mirror via an
#      ABSOLUTE path computed at runtime. The source replacement covers
#      reth-op AND every sibling monorepo crate (reth-optimism-evm,
#      reth-optimism-node, …) that reth-op's workspace pulls from the same
#      git source.
#
# Nothing this script writes is committed: the entire .vendor/ and .cargo/
# directories are gitignored. Cargo.toml declares the STABLE REMOTE url, so a
# clean checkout WITHOUT running this is still correct — cargo just clones the
# full multi-GB monorepo (slow). This script is the documented fast path and
# the required bootstrap for CI / Docker.
#
# Bump: do NOT hand-edit the OPTIMISM_REV default below. The lockstep bump is
# managed by scripts/bump-reth.sh (or `make bump`), which rewrites this
# OPTIMISM_REV default AND the matching revs in Cargo.toml together, then
# re-seeds and validates. The duplication of the optimism rev here (vs the
# `reth-op` rev in Cargo.toml) is INTENTIONAL — seed-vendor.sh must stand alone
# on a fresh machine without parsing Cargo.toml — and is kept synchronized by
# bump-reth.sh (which also refuses to run if it detects the two have drifted).
# To re-seed only (no rev change): delete .vendor/optimism and re-run.
set -euo pipefail

# --- Pinned rev (kept in lockstep with reth-op `rev` in Cargo.toml by
#     scripts/bump-reth.sh — do not hand-edit; see header) -------------------
OPTIMISM_REV="${OPTIMISM_REV:-8592d00d32afb4a0da959a2f14260c1d572e3a12}"
OPTIMISM_REMOTE="https://github.com/ethereum-optimism/optimism"

# --- Derive repo root from this script's location ---------------------------
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd -P)"

MIRROR="${REPO_ROOT}/.vendor/optimism"
CARGO_CONFIG="${REPO_ROOT}/.cargo/config.toml"

echo "seed-vendor: repo root   = ${REPO_ROOT}"
echo "seed-vendor: mirror      = ${MIRROR}"
echo "seed-vendor: optimism rev= ${OPTIMISM_REV}"

# --- 1. Shallow depth-1 mirror at the exact rev (idempotent) ----------------
need_clone=1
if [ -d "${MIRROR}/.git" ]; then
  have_rev="$(git -C "${MIRROR}" rev-parse HEAD 2>/dev/null || echo none)"
  if [ "${have_rev}" = "${OPTIMISM_REV}" ]; then
    echo "seed-vendor: mirror already at ${OPTIMISM_REV} — skipping clone"
    need_clone=0
  else
    echo "seed-vendor: mirror at ${have_rev} != wanted ${OPTIMISM_REV} — re-seeding"
    rm -rf "${MIRROR}"
  fi
fi

if [ "${need_clone}" -eq 1 ]; then
  mkdir -p "${MIRROR}"
  git -C "${MIRROR}" init -q
  git -C "${MIRROR}" remote add origin "${OPTIMISM_REMOTE}.git" 2>/dev/null || \
    git -C "${MIRROR}" remote set-url origin "${OPTIMISM_REMOTE}.git"
  git -C "${MIRROR}" -c protocol.version=2 fetch --depth 1 --no-tags origin "${OPTIMISM_REV}"
  git -C "${MIRROR}" branch -f develop FETCH_HEAD
  git -C "${MIRROR}" symbolic-ref HEAD refs/heads/develop
  git -C "${MIRROR}" checkout -q develop
  # Note: the inert `origin` remote is harmless. The "no promisor / no lazy
  # fetch" property comes from the shallow depth-1 fetch (the pack is
  # self-contained), NOT from removing the remote. We keep `origin` so a
  # future re-seed/bump can fetch a new rev without re-adding it.
  echo "seed-vendor: shallow depth-1 mirror created ($(du -sh "${MIRROR}/.git" | cut -f1) .git)"
fi

# --- 2. Generate the gitignored machine-local cargo config ------------------
# The whole .cargo/ dir is gitignored; this file is regenerated per machine.
# Absolute path is computed at runtime (cargo source replacement requires it).
mkdir -p "${REPO_ROOT}/.cargo"
cat > "${CARGO_CONFIG}" <<EOF
# GENERATED by scripts/seed-vendor.sh — DO NOT COMMIT (.cargo/ is gitignored).
# Machine-local: (1) use the system git binary so the shallow depth-1 local
# mirror clones correctly; (2) redirect the entire ethereum-optimism/optimism
# git source onto that mirror. The source replacement covers reth-op AND its
# sibling monorepo crates. The absolute path below is machine-specific by
# design and is why this file must never be committed; regenerate per machine
# / CI / Docker via scripts/seed-vendor.sh.

[net]
git-fetch-with-cli = true

[source."git+${OPTIMISM_REMOTE}?rev=${OPTIMISM_REV}"]
git = "${OPTIMISM_REMOTE}"
rev = "${OPTIMISM_REV}"
replace-with = "optimism-local-mirror"

[source.optimism-local-mirror]
git = "file://${MIRROR}"
rev = "${OPTIMISM_REV}"
EOF

echo "seed-vendor: wrote ${CARGO_CONFIG}"
echo "seed-vendor: done. Now run: cargo build -p spike --locked"
